CC = gcc
FLAGS = -Wall
SOURCE_PROGRAM_NAME = fork_and_exec_visual.c
PROGRAM_NAME = fork_and_exec_visual


all:
	make compile

compile:
	$(CC) $(FLAGS) $(SOURCE_PROGRAM_NAME) -o $(PROGRAM_NAME)

clean:
	rm -r $(PROGRAM_NAME)

clean_all:
	rm -r $(PROGRAM_NAME)
	rm -r $(DESTINATION_FILENAME)
	rm -r pomiar_zad_1.txt
