CC = gcc
FLAGS = -Wall -Werror
SOURCE_PROGRAM_NAME = dir_tree.c
PROGRAM_NAME = dir_tree

all:
	make compile

compile:
	$(CC) $(FLAGS) $(SOURCE_PROGRAM_NAME) -o $(PROGRAM_NAME)

clean:
	rm -r $(PROGRAM_NAME)	