CFLAGS = -Wall
CC = gcc

main: main.o

clean:
	rm -f main.o main

test:  main
	@echo -e "\n\nTESTING\n\n"
	./main /home/endrew/Uczelnia/Fizyka\ II /home/endrew/Downloads/ComputerVision-OCR/ComputerVision-master

all: main test