CC = gcc
FLAGS = -Wall
SOURCE_NAME = main.c
PROGRAM_NAME = main


compile:
	$(CC) $(FLAGS) $(SOURCE_NAME) -o $(PROGRAM_NAME)
run:
	$(CC) $(FLAGS) $(SOURCE_NAME) -o $(PROGRAM_NAME)
	./$(PROGRAM_NAME)

clean:
	rm -r main