CC = gcc
FLAGS = -Wall
SOURCE_PROGRAM_NAME = discover.c
PROGRAM_NAME = discover

compile:
	$(CC) $(FLAGS) $(SOURCE_PROGRAM_NAME) -o $(PROGRAM_NAME)

all:
	make compile
	./$(PROGRAM_NAME)

clean:
	rm -r $(PROGRAM_NAME)	