CC = gcc
FLAGS = -Wall
SOURCE_PROGRAM_NAME = dir_walk.c
PROGRAM_NAME = dir_walk

all:
	make compile

compile:
	$(CC) $(FLAGS) $(SOURCE_PROGRAM_NAME) -o $(PROGRAM_NAME)

clean:
	rm -r $(PROGRAM_NAME)

clean_all:
	rm -r $(PROGRAM_NAME)